name: Build APK - Simple

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Environment
      run: |
        # Setup Java
        sudo apt update
        sudo apt install -y openjdk-17-jdk
        
        # Setup Node.js
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt install -y nodejs
        
    - name: Install Cordova
      run: |
        npm install -g cordova@12.0.0
        
    - name: Setup Android SDK
      run: |
        # Download Android Command Line Tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk/cmdline-tools/latest
        mv cmdline-tools/* android-sdk/cmdline-tools/latest/
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        
        # Accept licenses dan install packages
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
        
    - name: Build APK
      run: |
        cordova platform add android@12.0.0
        cordova plugin add cordova-plugin-file
        cordova plugin add cordova-plugin-local-notification
        cordova build android --debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: quantum-trader-apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
